spring.application.name=Address-Service


spring.datasource.url=jdbc:postgresql://localhost:5433/Microservices
spring.datasource.username=postgres
spring.datasource.password=arun

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=address_schema

eureka.instance.hostname=localhost

eureka.client.service-url.defaultZone=http://localhost:5000/eureka/

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
eureka.instance.metadata-map.contextpath=address-app/api



management.endpoints.web.exposure.include=*
