


eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:5000/eureka/
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
management.endpoints.web.exposure.include=*

