spring.application.name=Employee-Service
spring.datasource.url=jdbc:postgresql://localhost:5433/Microservices
spring.datasource.username=postgres
spring.datasource.password=arun
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=employee_schema
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:5000/eureka/
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
management.endpoints.web.exposure.include=*

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
